[build]
  command = "npm run build"
  publish = "dist"
  base = "./"

[dev]
  command = "npm run dev"
  port = 5173  # Vite's default port
  target = "src"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
